"""add patient summary confirmations

Revision ID: 0e245ef8a3b8
Revises: 79781796eff9
Create Date: 2026-09-13 21:42:04.118215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e245ef8a3b8'
down_revision: Union[str, Sequence[str], None] = '79781796eff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_summary_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['medical_case_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_summary_confirmations_id'), 'patient_summary_confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmations_interview_id'), 'patient_summary_confirmations', ['interview_id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmations_patient_id'), 'patient_summary_confirmations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmations_status'), 'patient_summary_confirmations', ['status'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmations_summary_id'), 'patient_summary_confirmations', ['summary_id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmations_summary_version'), 'patient_summary_confirmations', ['summary_version'], unique=False)
    op.create_table('patient_summary_confirmation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('confirmation_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('summary_item_index', sa.Integer(), nullable=False),
    sa.Column('summary_item_text', sa.Text(), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('patient_response', sa.String(length=20), nullable=False),
    sa.Column('patient_correction', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmation_id'], ['patient_summary_confirmations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_summary_confirmation_items_confirmation_id'), 'patient_summary_confirmation_items', ['confirmation_id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmation_items_id'), 'patient_summary_confirmation_items', ['id'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmation_items_patient_response'), 'patient_summary_confirmation_items', ['patient_response'], unique=False)
    op.create_index(op.f('ix_patient_summary_confirmation_items_section_key'), 'patient_summary_confirmation_items', ['section_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_summary_confirmation_items_section_key'), table_name='patient_summary_confirmation_items')
    op.drop_index(op.f('ix_patient_summary_confirmation_items_patient_response'), table_name='patient_summary_confirmation_items')
    op.drop_index(op.f('ix_patient_summary_confirmation_items_id'), table_name='patient_summary_confirmation_items')
    op.drop_index(op.f('ix_patient_summary_confirmation_items_confirmation_id'), table_name='patient_summary_confirmation_items')
    op.drop_table('patient_summary_confirmation_items')
    op.drop_index(op.f('ix_patient_summary_confirmations_summary_version'), table_name='patient_summary_confirmations')
    op.drop_index(op.f('ix_patient_summary_confirmations_summary_id'), table_name='patient_summary_confirmations')
    op.drop_index(op.f('ix_patient_summary_confirmations_status'), table_name='patient_summary_confirmations')
    op.drop_index(op.f('ix_patient_summary_confirmations_patient_id'), table_name='patient_summary_confirmations')
    op.drop_index(op.f('ix_patient_summary_confirmations_interview_id'), table_name='patient_summary_confirmations')
    op.drop_index(op.f('ix_patient_summary_confirmations_id'), table_name='patient_summary_confirmations')
    op.drop_table('patient_summary_confirmations')
    # ### end Alembic commands ###
