"""add_patient_abha_links

Revision ID: 10977d263538
Revises: 6b7843dfa0a7
Create Date: 2026-09-13 22:41:09.096264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10977d263538'
down_revision: Union[str, Sequence[str], None] = '6b7843dfa0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to existing enums
    op.execute("ALTER TYPE consent_purpose_enum ADD VALUE IF NOT EXISTS 'ABHA_LINKAGE'")
    op.execute("ALTER TYPE privacy_audit_action_enum ADD VALUE IF NOT EXISTS 'ABHA_LINK_INITIATED'")
    op.execute("ALTER TYPE privacy_audit_action_enum ADD VALUE IF NOT EXISTS 'ABHA_LINK_VERIFIED'")
    op.execute("ALTER TYPE privacy_audit_action_enum ADD VALUE IF NOT EXISTS 'ABHA_LINK_FAILED'")
    op.execute("ALTER TYPE privacy_audit_action_enum ADD VALUE IF NOT EXISTS 'ABHA_UNLINKED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_abha_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('abha_id', sa.String(length=32), nullable=False),
    sa.Column('abha_address', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNLINKED', name='abha_link_status_enum', create_constraint=True), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', name='abha_verification_status_enum', create_constraint=True), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abha_id_status', 'patient_abha_links', ['abha_id', 'status'], unique=False)
    op.create_index('idx_patient_abha_status', 'patient_abha_links', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_patient_abha_links_abha_id'), 'patient_abha_links', ['abha_id'], unique=False)
    op.create_index(op.f('ix_patient_abha_links_id'), 'patient_abha_links', ['id'], unique=False)
    op.create_index(op.f('ix_patient_abha_links_patient_id'), 'patient_abha_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_abha_links_status'), 'patient_abha_links', ['status'], unique=False)
    op.create_index(op.f('ix_patient_abha_links_verification_status'), 'patient_abha_links', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_abha_links_verification_status'), table_name='patient_abha_links')
    op.drop_index(op.f('ix_patient_abha_links_status'), table_name='patient_abha_links')
    op.drop_index(op.f('ix_patient_abha_links_patient_id'), table_name='patient_abha_links')
    op.drop_index(op.f('ix_patient_abha_links_id'), table_name='patient_abha_links')
    op.drop_index(op.f('ix_patient_abha_links_abha_id'), table_name='patient_abha_links')
    op.drop_index('idx_patient_abha_status', table_name='patient_abha_links')
    op.drop_index('idx_abha_id_status', table_name='patient_abha_links')
    op.drop_table('patient_abha_links')
    # ### end Alembic commands ###
