"""add_privacy_and_consent

Revision ID: 6b7843dfa0a7
Revises: a05ec5e04a34
Create Date: 2026-09-13 22:26:52.892356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7843dfa0a7'
down_revision: Union[str, Sequence[str], None] = 'a05ec5e04a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('CLINICAL_HISTORY', 'DOCUMENT_PROCESSING', 'AI_SUMMARIZATION', 'BILINGUAL_OUTPUT', 'DATA_SHARING', name='consent_purpose_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'REVOKED', 'EXPIRED', 'SUPERSEDED', name='consent_status_enum', create_constraint=True), nullable=False),
    sa.Column('collection_method', sa.Enum('PATIENT_SELF', 'ASSISTED', 'DOCTOR_ASSISTED', name='consent_collection_method_enum', create_constraint=True), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('consent_text_ref', sa.String(length=100), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_consents_active', 'patient_consents', ['patient_id', 'purpose', 'status'], unique=False)
    op.create_index('idx_patient_consents_interview', 'patient_consents', ['patient_id', 'interview_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_patient_consents_id'), 'patient_consents', ['id'], unique=False)
    op.create_index(op.f('ix_patient_consents_interview_id'), 'patient_consents', ['interview_id'], unique=False)
    op.create_index(op.f('ix_patient_consents_patient_id'), 'patient_consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_consents_purpose'), 'patient_consents', ['purpose'], unique=False)
    op.create_index(op.f('ix_patient_consents_status'), 'patient_consents', ['status'], unique=False)
    op.create_table('privacy_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('CLINICAL_HISTORY', 'DOCUMENT_PROCESSING', 'AI_SUMMARIZATION', 'BILINGUAL_OUTPUT', 'DATA_SHARING', name='consent_purpose_enum'), nullable=False),
    sa.Column('action', sa.Enum('CONSENT_GRANTED', 'CONSENT_REVOKED', 'CONSENT_CHECKED', 'PROCESSING_BLOCKED', name='privacy_audit_action_enum', create_constraint=True), nullable=False),
    sa.Column('actor_type', sa.Enum('PATIENT', 'DOCTOR', 'SYSTEM', name='privacy_audit_actor_enum', create_constraint=True), nullable=False),
    sa.Column('actor_reference', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['patient_consents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_privacy_audit_patient_time', 'privacy_audit_logs', ['patient_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_action'), 'privacy_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_consent_id'), 'privacy_audit_logs', ['consent_id'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_id'), 'privacy_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_interview_id'), 'privacy_audit_logs', ['interview_id'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_patient_id'), 'privacy_audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_purpose'), 'privacy_audit_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_privacy_audit_logs_timestamp'), 'privacy_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_privacy_audit_logs_timestamp'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_purpose'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_patient_id'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_interview_id'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_id'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_consent_id'), table_name='privacy_audit_logs')
    op.drop_index(op.f('ix_privacy_audit_logs_action'), table_name='privacy_audit_logs')
    op.drop_index('idx_privacy_audit_patient_time', table_name='privacy_audit_logs')
    op.drop_table('privacy_audit_logs')
    op.drop_index(op.f('ix_patient_consents_status'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_purpose'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_patient_id'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_interview_id'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_id'), table_name='patient_consents')
    op.drop_index('idx_patient_consents_interview', table_name='patient_consents')
    op.drop_index('idx_patient_consents_active', table_name='patient_consents')
    op.drop_table('patient_consents')
    # ### end Alembic commands ###
