"""add medical case summaries

Revision ID: 79781796eff9
Revises: f413917f2c2b
Create Date: 2026-09-13 19:56:44.255614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79781796eff9'
down_revision: Union[str, Sequence[str], None] = 'f413917f2c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_case_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('summary_status', sa.String(length=20), nullable=False),
    sa.Column('summary_language', sa.String(length=10), nullable=False),
    sa.Column('summary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'summary_version', name='uq_case_summary_interview_version')
    )
    op.create_index(op.f('ix_medical_case_summaries_id'), 'medical_case_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_medical_case_summaries_interview_id'), 'medical_case_summaries', ['interview_id'], unique=False)
    op.create_index(op.f('ix_medical_case_summaries_patient_id'), 'medical_case_summaries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_case_summaries_summary_status'), 'medical_case_summaries', ['summary_status'], unique=False)
    op.create_index(op.f('ix_medical_case_summaries_summary_version'), 'medical_case_summaries', ['summary_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_case_summaries_summary_version'), table_name='medical_case_summaries')
    op.drop_index(op.f('ix_medical_case_summaries_summary_status'), table_name='medical_case_summaries')
    op.drop_index(op.f('ix_medical_case_summaries_patient_id'), table_name='medical_case_summaries')
    op.drop_index(op.f('ix_medical_case_summaries_interview_id'), table_name='medical_case_summaries')
    op.drop_index(op.f('ix_medical_case_summaries_id'), table_name='medical_case_summaries')
    op.drop_table('medical_case_summaries')
    # ### end Alembic commands ###
