"""add_bilingual_summary_outputs

Revision ID: a05ec5e04a34
Revises: a383e258e91c
Create Date: 2026-09-13 22:14:59.138919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05ec5e04a34'
down_revision: Union[str, Sequence[str], None] = 'a383e258e91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilingual_summary_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('source_language_code', sa.String(length=10), nullable=False),
    sa.Column('target_language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_summary', sa.JSON(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('output_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['medical_case_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id', 'summary_version', 'target_language_code', name='uq_summary_version_target_language')
    )
    op.create_index(op.f('ix_bilingual_summary_outputs_id'), 'bilingual_summary_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_interview_id'), 'bilingual_summary_outputs', ['interview_id'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_output_status'), 'bilingual_summary_outputs', ['output_status'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_patient_id'), 'bilingual_summary_outputs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_summary_id'), 'bilingual_summary_outputs', ['summary_id'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_summary_version'), 'bilingual_summary_outputs', ['summary_version'], unique=False)
    op.create_index(op.f('ix_bilingual_summary_outputs_target_language_code'), 'bilingual_summary_outputs', ['target_language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bilingual_summary_outputs_target_language_code'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_summary_version'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_summary_id'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_patient_id'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_output_status'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_interview_id'), table_name='bilingual_summary_outputs')
    op.drop_index(op.f('ix_bilingual_summary_outputs_id'), table_name='bilingual_summary_outputs')
    op.drop_table('bilingual_summary_outputs')
    # ### end Alembic commands ###
