"""add_doctor_summary_reviews

Revision ID: a383e258e91c
Revises: 0e245ef8a3b8
Create Date: 2026-09-13 22:05:22.104864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a383e258e91c'
down_revision: Union[str, Sequence[str], None] = '0e245ef8a3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_summary_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['medical_case_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_summary_reviews_doctor_id'), 'doctor_summary_reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_id'), 'doctor_summary_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_interview_id'), 'doctor_summary_reviews', ['interview_id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_patient_id'), 'doctor_summary_reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_status'), 'doctor_summary_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_summary_id'), 'doctor_summary_reviews', ['summary_id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_reviews_summary_version'), 'doctor_summary_reviews', ['summary_version'], unique=False)
    op.create_table('doctor_summary_review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('summary_item_index', sa.Integer(), nullable=False),
    sa.Column('original_ai_text', sa.Text(), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('doctor_response', sa.String(length=20), nullable=False),
    sa.Column('doctor_correction', sa.Text(), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_confirmation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['doctor_summary_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_summary_review_items_doctor_response'), 'doctor_summary_review_items', ['doctor_response'], unique=False)
    op.create_index(op.f('ix_doctor_summary_review_items_id'), 'doctor_summary_review_items', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_review_items_review_id'), 'doctor_summary_review_items', ['review_id'], unique=False)
    op.create_index(op.f('ix_doctor_summary_review_items_section_key'), 'doctor_summary_review_items', ['section_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_summary_review_items_section_key'), table_name='doctor_summary_review_items')
    op.drop_index(op.f('ix_doctor_summary_review_items_review_id'), table_name='doctor_summary_review_items')
    op.drop_index(op.f('ix_doctor_summary_review_items_id'), table_name='doctor_summary_review_items')
    op.drop_index(op.f('ix_doctor_summary_review_items_doctor_response'), table_name='doctor_summary_review_items')
    op.drop_table('doctor_summary_review_items')
    op.drop_index(op.f('ix_doctor_summary_reviews_summary_version'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_summary_id'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_status'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_patient_id'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_interview_id'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_id'), table_name='doctor_summary_reviews')
    op.drop_index(op.f('ix_doctor_summary_reviews_doctor_id'), table_name='doctor_summary_reviews')
    op.drop_table('doctor_summary_reviews')
    # ### end Alembic commands ###
