"""create_clinical_ontology_tables

Revision ID: cba74366733a
Revises: cabbf8921063
Create Date: 2026-09-13 16:28:56.404677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba74366733a'
down_revision: Union[str, Sequence[str], None] = 'cabbf8921063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_ontology_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_ontology_fields_field_key'), 'clinical_ontology_fields', ['field_key'], unique=True)
    op.create_index(op.f('ix_clinical_ontology_fields_id'), 'clinical_ontology_fields', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_ontology_fields_section'), 'clinical_ontology_fields', ['section'], unique=False)
    op.create_table('interview_clinical_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('collection_status', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_key'], ['clinical_ontology_fields.field_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'field_key', name='uq_interview_field_key')
    )
    op.create_index(op.f('ix_interview_clinical_data_collection_status'), 'interview_clinical_data', ['collection_status'], unique=False)
    op.create_index(op.f('ix_interview_clinical_data_field_key'), 'interview_clinical_data', ['field_key'], unique=False)
    op.create_index(op.f('ix_interview_clinical_data_id'), 'interview_clinical_data', ['id'], unique=False)
    op.create_index(op.f('ix_interview_clinical_data_interview_id'), 'interview_clinical_data', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_clinical_data_interview_id'), table_name='interview_clinical_data')
    op.drop_index(op.f('ix_interview_clinical_data_id'), table_name='interview_clinical_data')
    op.drop_index(op.f('ix_interview_clinical_data_field_key'), table_name='interview_clinical_data')
    op.drop_index(op.f('ix_interview_clinical_data_collection_status'), table_name='interview_clinical_data')
    op.drop_table('interview_clinical_data')
    op.drop_index(op.f('ix_clinical_ontology_fields_section'), table_name='clinical_ontology_fields')
    op.drop_index(op.f('ix_clinical_ontology_fields_id'), table_name='clinical_ontology_fields')
    op.drop_index(op.f('ix_clinical_ontology_fields_field_key'), table_name='clinical_ontology_fields')
    op.drop_table('clinical_ontology_fields')
    # ### end Alembic commands ###
