"""add medical timeline events

Revision ID: e9a529eec7e0
Revises: c85042975676
Create Date: 2026-09-13 19:38:49.046909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9a529eec7e0'
down_revision: Union[str, Sequence[str], None] = 'c85042975676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.Column('normalized_date', sa.Date(), nullable=True),
    sa.Column('event_date_precision', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['medical_document_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_timeline_events_document_id'), 'medical_timeline_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_event_date_precision'), 'medical_timeline_events', ['event_date_precision'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_event_type'), 'medical_timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_extraction_id'), 'medical_timeline_events', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_id'), 'medical_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_interview_id'), 'medical_timeline_events', ['interview_id'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_normalized_date'), 'medical_timeline_events', ['normalized_date'], unique=False)
    op.create_index(op.f('ix_medical_timeline_events_patient_id'), 'medical_timeline_events', ['patient_id'], unique=False)
    op.create_index('ix_timeline_patient_date', 'medical_timeline_events', ['patient_id', 'normalized_date'], unique=False)
    op.create_index('ix_timeline_interview_date', 'medical_timeline_events', ['interview_id', 'normalized_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_interview_date', table_name='medical_timeline_events')
    op.drop_index('ix_timeline_patient_date', table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_patient_id'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_normalized_date'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_interview_id'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_id'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_extraction_id'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_event_type'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_event_date_precision'), table_name='medical_timeline_events')
    op.drop_index(op.f('ix_medical_timeline_events_document_id'), table_name='medical_timeline_events')
    op.drop_table('medical_timeline_events')
    # ### end Alembic commands ###
