from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.models.bilingual_summary_output import BilingualOutputStatus
from app.schemas.case_summary import StructuredCaseSummary, SummarySourceRef


class BilingualSummaryGenerateRequest(BaseModel):
    target_language_code: Optional[str] = Field(
        None,
        description="Target language code (e.g. 'mr', 'hi'). If omitted, falls back to interview/patient language.",
    )


class BilingualSectionItem(BaseModel):
    text: str
    sources: List[SummarySourceRef] = Field(default_factory=list)
    status: Optional[str] = None


class BilingualSection(BaseModel):
    display_label: str
    items: List[BilingualSectionItem] = Field(default_factory=list)


class BilingualTranslatedSummary(BaseModel):
    language_code: str
    language_name: str
    sections: Dict[str, BilingualSection] = Field(default_factory=dict)


class BilingualSummaryResponse(BaseModel):
    id: Optional[int] = None
    patient_id: int
    interview_id: int
    summary_id: int
    summary_version: int
    canonical_language_code: str = "en"
    target_language_code: str
    target_language_name: Optional[str] = None
    is_bilingual: bool
    output_status: str
    provider_name: Optional[str] = None
    model_name: Optional[str] = None
    error_message: Optional[str] = None
    english: StructuredCaseSummary
    translated: Optional[BilingualTranslatedSummary] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    disclaimer: str = Field(
        default=(
            "DRAFT summary generated by AI for physician review only. "
            "Does not constitute a clinical diagnosis or treatment recommendation. "
            "Translated text is an assistive presentation layer; clinical decisions "
            "must rely on the canonical verified case record."
        )
    )

    model_config = ConfigDict(from_attributes=True)


class BilingualSummaryStatusItem(BaseModel):
    id: int
    summary_id: int
    summary_version: int
    target_language_code: str
    target_language_name: Optional[str] = None
    output_status: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class BilingualSummaryListResponse(BaseModel):
    interview_id: int
    summary_id: int
    summary_version: int
    total_outputs: int
    outputs: List[BilingualSummaryStatusItem] = Field(default_factory=list)
