from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.models.medical_case_summary import SummaryStatus


class SummarySourceRef(BaseModel):
    source_type: str = Field(..., description="INTERVIEW, DOCUMENT_EXTRACTION, TIMELINE, ABNORMAL_VALUE")
    field_key: Optional[str] = None
    document_id: Optional[int] = None
    extraction_id: Optional[int] = None
    timeline_event_id: Optional[int] = None
    investigation_result_id: Optional[int] = None
    source_page: Optional[int] = None
    source_text: Optional[str] = None


class SummaryItem(BaseModel):
    text: str
    sources: List[SummarySourceRef] = Field(default_factory=list)
    status: Optional[str] = None


class CaseSheetSection(BaseModel):
    items: List[SummaryItem] = Field(default_factory=list)


class StructuredCaseSummary(BaseModel):
    chief_complaint: CaseSheetSection = Field(default_factory=CaseSheetSection)
    history_of_present_illness: CaseSheetSection = Field(default_factory=CaseSheetSection)
    past_medical_history: CaseSheetSection = Field(default_factory=CaseSheetSection)
    medication_history: CaseSheetSection = Field(default_factory=CaseSheetSection)
    allergy_history: CaseSheetSection = Field(default_factory=CaseSheetSection)
    family_history: CaseSheetSection = Field(default_factory=CaseSheetSection)
    personal_history: CaseSheetSection = Field(default_factory=CaseSheetSection)
    review_of_systems: CaseSheetSection = Field(default_factory=CaseSheetSection)
    ayush_profile: Optional[CaseSheetSection] = None


class CaseSummaryResponse(BaseModel):
    id: int
    patient_id: int
    interview_id: int
    summary_version: int
    summary_status: SummaryStatus
    summary_language: str
    summary_data: Optional[StructuredCaseSummary] = None
    provider_name: str
    model_name: Optional[str] = None
    processing_error: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    disclaimer: str = Field(
        default="DRAFT summary generated by AI for physician review only. Does not constitute a clinical diagnosis or treatment recommendation.",
        description="Mandatory clinical decision-support disclaimer",
    )

    model_config = ConfigDict(from_attributes=True)


class CaseSummaryListResponse(BaseModel):
    interview_id: int
    patient_id: int
    total_summaries: int
    summaries: List[CaseSummaryResponse]
